version: "2.4"
services:
  wss-server:
    container_name: "wss-server"
    build:
      context: .
      dockerfile: Dockerfile-redis-jedis
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - SPRING_PROFILES_ACTIVE=prod
      - WSS_MODEL_INITIALIZE=true
      - WSS_MODEL_WAREHOUSE_COUNT=5
      - WSS_MODEL_FULL_SCALE=true
      - WSS_REDIS_JEDIS_POOL_MAX-TOTAL=32
      - WSS_REDIS_JEDIS_POOL_MAX-IDLE=16
      - WSS_REDIS_JEDIS_POOL_MIN-IDLE=8
      - JAVA_OPTS=-Xmx14G
    cpu_count: 4
    mem_reservation: 12g
    mem_limit: 14g

  db:
    container_name: "wss-redis-jedis"
    image: "redis"
    volumes:
      - /var/lib/redis/data
    ports:
      - "6379:6379"
volumes:
  redis_data:

